/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";
import { useRef } from "react";
import { useFrame } from "@react-three/fiber";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./landing-world/earth.gltf");

  const meshRef = useRef<Mesh | null>(null);

  useFrame(() => {
    if (meshRef.current) {
      meshRef.current.rotation.y += 0.002;
    }
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={(nodes.Object_4 as Mesh).geometry}
        material={materials["Scene_-_Root"]}
        scale={1.828}
      />
    </group>
  );
}

useGLTF.preload("./landing-world/earth.gltf");
